<?php

/**
 * Delimiter for extracting a part of a field.
 */
define('DING_WAYF_FIELD_DELIMITER', ':');
define('DING_WAYF_BASE_URL', 'https://bibliotek.dk');

/**
 * Implements hook_permission().
 */
function ding_wayf_permission() {
  return array(
    'configure wayf' => array(
      'title' => t('Configure WAYF'),
      'description' => t('Allow role to configure WAYF settings.'),
    ),
  );
}


/**
 * Implements hook_menu().
 */
function ding_wayf_menu() {
  $items = array();
  // config page
  $items['admin/config/ding/wayf'] = array(
    'title' => t('WAYF'),
    'description' => t('Configure WAYF'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_wayf_admin_settings_form'),
    'access arguments' => array('configure wayf'),
    'file' => 'includes/ding_wayf.admin.inc',
  );
  // login page
  $items['wayf/login'] = array(
    'title' => t('Logon to the site'),
    'description' => t('Provides WAYF login.'),
    'page callback' => 'ding_wayf_redirect_login',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  // accept page
  $items['wayf/accept'] = array(
    'title' => t('WAYF_ACCEPT'),
    'description' => t('Provides WAYF login.'),
    'page callback' => 'ding_wayf_accept',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/** \brief accept page callback
 *
 */
function ding_wayf_accept() {
  drupal_get_messages();
  // add an accept form if provider implements it
  if (ding_provider_implements('wayf', 'accept_form')) {
    $form = ding_provider_invoke('wayf', 'accept_form');
    $render_array = drupal_get_form($form);
    return drupal_render($render_array);
  }
}

/** Implements hook_init
 *
 * special case; user was authenticated with wayf, but for some reason
 * not with drupal - maybe user aborted while logging in.
 * make sure SESSION variables are removed, and user is logged out of wayf
 *
 * @global type $user
 */
function ding_wayf_init() {
  if (isset($_SESSION['wayf_login'])) {
    if (isset($_GET['idp'])) {
      $loginType = $_GET['idp'];
      if ($loginType == 'wayf') {
        $loginType = 'wayf_id';
      }
      elseif ($loginType == 'nemlogin') {
        $loginType = 'nem_id';
      }
      if ($_SESSION['wayf_login']['login_type'] != $loginType) {
        drupal_set_message(t('Something went wrong. Please try again', array(), array('context' => 'ding_wayf')), 'warning');
        ding_wayf_user_logout();
      }
    }
  }
}

/** \brief Login a wayf user, as thay where logged in by the library system.
 * easy solution; fake form_state and submit user_login form. In that way
 * ding_user handles user-login as always.
 *
 * pre; user is authenticated via wayf or we wouldn't be here
 */
function ding_wayf_login($authentication_attributes, $notify_by_mail = NULL) {
  global $user;
  if ($user->uid == 0) {
    $form_state = array();
    // get form_state from provider
    $form_state = ding_provider_invoke('wayf', 'login_creds', $authentication_attributes, $notify_by_mail);

    // submit login form
    drupal_form_submit('user_login_block', $form_state);
    $errors = form_get_errors();
    if (!empty($errors)) {
      drupal_goto('user');
    }
  }
  else {
    drupal_goto('user/' . $user->uid . '/edit');
  }
}

/** Implements hook_form_FORM_ID_alter (user_login)
 *
 * add wayf login block to form['actions']
 */
function ding_wayf_form_user_login_alter(&$form, &$form_state) {
  $config = variable_get('ding_wayf', NULL);
  /*if ($config['nemlogin']) {
    $form['login_methods'][] = ding_wayf_get_nemlogin();
  }*/
  if ($config['wayflogin']) {
    $form['login_methods'][] = ding_wayf_get_wayflogin();
  }
}

/**
 * Implements hook_form_alter() (user_login, user_login_block).
 * add hidden field to set authentication provider
 * add validate handler for wayf login
 */
function ding_wayf_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'user_login':
    case 'user_login_block':
      // option to set authentication provider for ding user (@see ding_user_user_login_validate)
      $form['authentication_provider'] = array(
        '#type' => 'hidden',
      );
      // add a validation handler (if provider implements it)
      $provider = ding_provider_get_provider_module_name('wayf');
      if (isset($provider)) {
        $function = $provider . '_wayf_validate';
        if (function_exists($function)) {
          //$form['#validate'][] = $function;
          array_unshift($form['#validate'], $function);
        }
      }

      break;
    default:
      break;
  }
}

/**
 * Helper function that handles the login procedure. If the user is not yet
 * authenticated by WAYF - the user will be redirected to WAYF login. If the
 * user is authenticated the user will be logged into the drupal site as a
 * library user.
 *
 * The library system may block the user and he/she will automaticly be logged
 * out of WAYF.
 *
 * If the user is logged into both system, the user will be redirecte to a
 * preconfigured URL.
 */
function ding_wayf_redirect_login() {
  global $user;
  if ($user->uid == 0) {
    $saml = ding_wayf_get_saml_connection();
    if ($saml->isAuthenticated()) {
      $wayf_data = $saml->getAttributes();

      // get salt to use for hast
      $config = variable_get('ding_wayf', NULL);

      $freeze = array(
        $wayf_data['schacPersonalUniqueID'][0],
        $wayf_data['eduPersonTargetedID'][0]
      );
      $hash = ding_wayf_safety_hash($freeze);
      $salt = $config['safetyhash'];
      $safetyhash = md5($hash . $salt);

      //compare with hash given from gatewayf - if no match abort
      if ($safetyhash !== $wayf_data['hash'][0]) {
        ding_wayf_user_logout();
      }

      $authentication_attributes = ding_wayf_get_authentication_attributes($wayf_data);
      //log user in
      ding_wayf_login($authentication_attributes);
    }
    else {
      $idp = $_GET['idp'];
      $idps = ding_wayf_idps();
      // Redirect the user to the WAYF login page.
      $saml->requireAuth($idps[$idp]);
    }
  }
  else {
    // Send the user back to her context or use the fallback URL.
    ding_wayf_redirect_user();
  }
}


/**
 * Make a cachekey based on request parameters
 *
 * @param array $params
 * @param string $ret
 **/
function ding_wayf_safety_hash($params, $ret = '') {
  foreach ($params as $key => $value) {
    //$ret .= $key;
    if (is_array($value)) {
      // recursive
      $ret = ding_wayf_safety_hash($value, $ret);
    }
    else {
      $ret .= $value;
    }
  }
  return $ret;
}


/**
 * Helper function that redirectes the user to previous context or the fallback
 * URL given as parameter.
 *
 * @param string $url
 */
function ding_wayf_redirect_user($url = null) {
  if (!empty($_REQUEST['destination'])) {
    $url = $_REQUEST['destination'];
  }
  else {
    global $user;
    $url = str_replace('%uid', $user->uid, $url);
  }

  drupal_goto($url);
}

/** Implements hook_user_delete
 *  log user out of simplesaml
 */
function ding_wayf_user_delete($account) {
  ding_wayf_user_logout($account);
}

/**
 * Implementation of hook_user_logout().
 *
 * Ensures that the WAYF logout function is called on user logout.
 *
 * @param $account
 *   account of logged in user.
 */
function ding_wayf_user_logout($account = NULL, $origin = NULL) {
  global $base_url;

  $url = NULL;
  $saml = ding_wayf_get_saml_connection();

  if (!empty($saml)) {
    if ($saml->isAuthenticated()) {
      if (isset($_SESSION['accept_wayf'])) {
        // unset _SESSION variables
        unset($_SESSION['accept_wayf']);
      }
      if (isset($origin)) {
        $url = DING_WAYF_BASE_URL . '/' . $origin;
      }
      // we pass simplesaml the url to return to -
      // you can pass simplesaml::logout an array of values ['ReturnTo', 'ReturnCallback'] etc.
      // if only a string is passed it will be handled as 'ReturnTo'
      $saml->logout($url);
    }
  }
}

/**
 * Helper function that extracts a field from a saml attribute string.
 *
 * @param string $data
 * @param string $field
 * @return string
 */
function ding_wayf_extract_data($data, $field = FALSE) {
  if (empty($field)) {
    return $data[0];
  }
  else {
    $field .= DING_WAYF_FIELD_DELIMITER;

    if (($pos = strpos($data[0], $field)) !== FALSE) {
      return substr($data[0], $pos + strlen($field));
    }
    else {
      return '';
    }
  }
}

/**
 * Gets a connection to simple saml php.
 *
 * @param string $sp
 * @return SimpleSAML_Auth_Simple|bool
 */
function ding_wayf_get_saml_connection($sp = NULL) {
  $simplesaml = variable_get('ding_wayf', array());

  if (empty($simplesaml)) {
    drupal_set_message(t('The WAYF login module is not configured yet, plase contact the site administrator.'), 'error', FALSE);
    ding_wayf_redirect_user('<front>');
  }

  if (!empty($simplesaml)) {
    // require_once $simplesaml['installdir'] . '/lib/_autoload.php';
    //require_once('/lib/_autoload.php');
    module_load_include('php', 'ding_wayf', 'lib/_autoload');
    $sp = $simplesaml['sp'];
    return new SimpleSAML_Auth_Simple($sp);
  }
  return FALSE;
}

/**
 * Check that simpleSAMLphp is installed at the location given.
 */
function ding_wayf_check_simplesamlphp($path) {
  return file_exists($path . '/lib/_autoload.php');
}

/**
 * Get logo image
 * @param $path
 *   path to the image
 * @param $alt_text
 *   alt text for the image
 * @return string
 *   rendered array
 */
function ding_wayf_get_logo($path, $alt_text) {
  $logo_path = base_path() . drupal_get_path('theme', $GLOBALS['theme']);
  $logo_path .= $path;
  $image = array(
    '#theme' => 'image',
    '#path' => $logo_path,
    '#alt' => $alt_text,
    '#title' => 'login logo',
  );
  return drupal_render($image);
}

/**
 * Get a render array for nemlogin
 * @return array
 *   render array for drupal_render
 */
function ding_wayf_get_nemlogin(){
  $wrapper = ding_wayf_login_wrapper();
  $wrapper['helptxt'] = array(
    '#type' => 'html_tag',
    '#tag' => 'h2',
    '#value' => t('NEMID_leadtext', array(), array('options'=>array('context' => 'ding_wayf'))),
  );
  $wrapper['link'] = ding_wayf_get_nemlogin_link();
  return $wrapper;
}

/**
 * Get a render array for wayf login
 * @return array
 *   Render array for drupal_render
 */
function ding_wayf_get_wayflogin(){
  $wrapper = ding_wayf_login_wrapper();
  $wrapper['helptxt'] = array(
    '#type' => 'html_tag',
    '#tag' => 'h2',
    '#value' => t('WAYF_leadtext', array(), array('options'=>array('context' => 'ding_wayf'))),
  );
  $wrapper['link'] = ding_wayf_get_wayf_link();
  return $wrapper;
}

/**
 * Get a link for wayf login (with a logo)
 * @return array
 *  Render array for drupal_render
 */
function ding_wayf_get_wayf_link(){
  $logo_path = '/img/in_use/wayf-logo.png';
  $logo_alt_text_nemid = t('logo_alt_text_wayf', array(), array('context' => 'ding_wayf'));

  $wrapper = ding_wayf_login_wrapper();
  //$wrapper['#attributes'] = array('class'=>array('bibdk-login-method'));
  $wrapper['link'] = array(
    '#type' => 'link',
    '#href' =>'wayf/login',
    '#title' => ding_wayf_get_logo($logo_path, $logo_alt_text_nemid),
    '#options' => array(
      'html' => TRUE,
      'attributes' => array('class' => 'wayflogin-logo'),
      'query' => array('idp' => 'wayf', drupal_get_destination()),
    ),
  );

  return $wrapper;
}

/**
 * Get a link for nemlogin
 * @return array
 *   Render array for drupal_render
 */
function ding_wayf_get_nemlogin_link(){
  $logo_path = '/img/in_use/nemid-logo.png';
  $logo_alt_text_nemid = t('logo_alt_text_nemid', array(), array('context' => 'ding_wayf'));

  $wrapper = ding_wayf_login_wrapper();
  //$wrapper['#attributes'] = array('class'=>array('bibdk-login-method'));
  $wrapper['link'] = array(
    '#type' => 'link',
    '#href' =>'wayf/login',
    '#title' => ding_wayf_get_logo($logo_path, $logo_alt_text_nemid),
    '#options' => array(
      'html' => TRUE,
      'attributes' => array('class' => array('nemlogin-logo')),
      'query' => array('idp' => 'nemlogin', drupal_get_destination()),
    ),
  );

  return $wrapper;
}

/**
 * Get a wrapper for a login method
 * @return array
 */
function ding_wayf_login_wrapper(){
  $wrapper = array(
    '#type' => 'container',
    '#attributes' => array('class'=>array('bibdk-login-method')),
  );
  return $wrapper;
}

/** \brief get the valid idp's
 *
 */
function ding_wayf_idps() {
  $ret = array(
    'test' => 'test',
    'wayf' => 'wayf',
    'nemlogin' => 'nemlogin',
  );

  return $ret;
}

/**
 * Sets attributes if specified by Ding provider.
 */
function ding_wayf_get_provider_attributes(&$simplesaml) {
  $wayf_attributes = module_invoke_all('ding_wayf_attributes');

  if ($wayf_attributes) {
    $simplesaml['attributes'] = $wayf_attributes;
  }
}

/** Get authentication attributes
 *
 * @param $wayf_data
 * @return array
 */
function ding_wayf_get_authentication_attributes($wayf_data) {
  // required attributes
  $simplesaml = variable_get('ding_wayf', array());
  ding_wayf_get_provider_attributes($simplesaml);
  $required_attributes = $simplesaml['attributes'];

  return ding_wayf_get_required_attributes($wayf_data, $required_attributes);
}

/**
 * Extract required attributes from available WAYF attributes.
 *
 * @param $wayf_attributes
 *   array of WAYF attributes
 * @param $required_attributes
 *   array of required attributes
 * @return
 *   array of attributes which will be empty if not all required attributes is
 *   present.
 */
function ding_wayf_get_required_attributes($wayf_attributes, $required_attributes) {

  $attribute_list = array();

  if (isset($_SESSION['accept_wayf']['name'])) {
    $wayf_attributes['mail'][0] = $_SESSION['accept_wayf']['name'];
  }

  if (isset($wayf_attributes) && is_array($required_attributes)) {
    foreach ($required_attributes as $attribute => $value) {
      if (isset($wayf_attributes[$attribute])) {
        $attribute_list[$attribute] = $wayf_attributes[$attribute];
      }
    }

    return $attribute_list;
  }
  else {
    return array();
  }
}

